# Generated by Django 2.2.6 on 2019-12-09 14:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_details',
            name='user',
            field=models.ForeignKey(on_delete=False, related_name='user_detail', to=settings.AUTH_USER_MODEL, verbose_name='Kullanici Adi'),
        ),
    ]
