# Generated by Django 2.2.6 on 2019-12-09 22:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('designs', '0002_auto_20191209_1711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='design',
            name='user',
            field=models.ForeignKey(on_delete=False, related_name='designs', to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı'),
        ),
    ]
