# Generated by Django 2.2.6 on 2019-12-09 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adverts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertview',
            name='ip',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='advertview',
            name='session',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
