# Generated by Django 2.2.6 on 2019-12-09 22:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adverts', '0002_auto_20191209_1710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advert',
            name='user',
            field=models.ForeignKey(on_delete=False, related_name='adverts', to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı'),
        ),
    ]
